name: 'Report'
description: 'Report DyLin results'

runs:
  using: 'composite'
  steps:
    - name: Setup temp directory
      shell: bash
      run: |
        python -c "import tempfile; print(f'TMPDIR={tempfile.gettempdir()}')" >> $GITHUB_ENV

    - name: Collect results
      shell: bash
      run: python -m dynapyt.post_run --coverage_dir=${{ env.TMPDIR }}/dynapyt_coverage-1234-abcd --output_dir=${{ env.TMPDIR }}/dynapyt_output-1234-abcd
    
    - name: Report results
      shell: bash
      run: cat ${{ env.TMPDIR }}/dynapyt_output-1234-abcd/output.json >> $GITHUB_STEP_SUMMARY