name: 'Report'
description: 'Report DyLin results'

runs:
  using: 'composite'
  steps:
    - name: Collect results
      shell: bash
      run: python -m dynapyt.post_run --coverage_dir=${{ env.TMPDIR }}${{ env.SEP }}dynapyt_coverage-${{ env.DYNAPYT_SESSION_ID }} --output_dir=${{ env.TMPDIR }}${{ env.SEP }}dynapyt_output-${{ env.DYNAPYT_SESSION_ID }}
    
    - name: Write results to file
      shell: bash
      run: python -m dylin.format_output --findings_path=${{ env.TMPDIR }}${{ env.SEP }}dynapyt_output-${{ env.DYNAPYT_SESSION_ID }}${{ env.SEP }}output.json >> ./findings.txt
    
    - name: Download old results
      uses: dawidd6/action-download-artifact@v6
      with:
        name: report
        path: ./old_findings.txt
        workflow_search: true
        search_artifacts: true
        if_no_artifact_found: ignore
    
    - name: Report changes
      shell: bash
      run: |
        echo "## Changes in Findings\n" >> $GITHUB_STEP_SUMMARY
        diff ./old_findings.txt ./findings.txt >> $GITHUB_STEP_SUMMARY
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: ./findings.txt
        retention-days: 2
    
    - name: Report results to summary
      shell: bash
      run: |
        echo "## Latest Findings\n" >> $GITHUB_STEP_SUMMARY
        cat ./findings.txt >> $GITHUB_STEP_SUMMARY