name: 'Report'
description: 'Report DyLin results'

runs:
  using: 'composite'
  steps:
    - name: Collect results
      shell: bash
      run: python -m dynapyt.post_run --coverage_dir=${{ env.TMPDIR }}/dynapyt_coverage-${{ env.DYNAPYT_SESSION_ID }} --output_dir=${{ env.TMPDIR }}/dynapyt_output-${{ env.DYNAPYT_SESSION_ID }}
    
    - name: Report results
      shell: bash
      run: cat ${{ env.TMPDIR }}/dynapyt_output-${{ env.DYNAPYT_SESSION_ID }}/output.json >> $GITHUB_STEP_SUMMARY