name: 'Instrument'
description: 'Instrument code according to DyLin analyses'

inputs:
  path:
    description: 'Path to instrument'
    required: false
    default: '.'
  include-checkers:
    description: 'Checkers to run'
    required: false
    default: 'All'
  exclude-checkers:
    description: 'Checkers that will not run'
    required: false
    default: 'None'
  analysis-coverage:
    description: 'Whether to collect analysis coverage'
    required: false
    default: true

runs:
  using: 'composite'
  steps:
    - name: Checkout DyLin
      uses: actions/checkout@v4
      with:
        repository: 'AryazE/DyLin'
        path: 'DyLin'
        ref: 'main'

    - name: Install DyLin
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ./DyLin/requirements.txt
        pip install ./DyLin
    
    - name: Remove DyLin files
      shell: bash
      run: rm -rf ./DyLin
    
    - name: Set session id
      shell: bash
      run: echo "DYNAPYT_SESSION_ID=1234-abcd" >> $GITHUB_ENV

    - name: Setup temp directory
      shell: bash
      run: |
        python -c "import tempfile; print(f'TMPDIR={tempfile.gettempdir()}')" >> $GITHUB_ENV
 
    - name: Select analyses
      shell: bash
      run: python -m dylin.select_checkers --include="${{ inputs['include-checkers'] }}" --exclude="${{ inputs['exclude-checkers'] }}" --output_dir=${{ env.TMPDIR }}/dynapyt_output-${{ env.DYNAPYT_SESSION_ID }} > analyses.txt
    
    - name: Instrument
      shell: bash
      run: python -m dynapyt.run_instrumentation --directory=${{ inputs.path }} --analysis=analyses.txt
    
    - name: Set coverage path
      if: ${{ inputs['analysis-coverage'] }}
      shell: bash
      run: |
        echo "DYNAPYT_COVERAGE=${{ env.TMPDIR }}/dynapyt_coverage-${{ env.DYNAPYT_SESSION_ID }}" >> $GITHUB_ENV

    - name: Copy analyses.txt
      shell: bash
      run: cp analyses.txt ${{ env.TMPDIR }}/dynapyt_analyses-${{ env.DYNAPYT_SESSION_ID }}.txt

  