name: Analyze GitHub Repo

on:
    workflow_dispatch:
        inputs:
            repository:
                description: 'Repository to analyze'
                required: true
            sha:
                description: 'SHA of the commit to analyze'
                required: false
                default: ''
            test_workflow:
                description: 'Test workflow'
                required: true

jobs:
    analyze:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            
            - name: Checkout target repository
              uses: actions/checkout@v4
              with:
                repository: ${{ inputs.repository }}
                ref: ${{ inputs.sha }}
                path: 'target_repo'
            
            - name: Checkout DyLin
              uses: actions/checkout@v4
              with:
                repository: 'AryazE/DyLin'
                ref: 'main'
                path: 'DyLin'
            
            - name: Install DyLin
              run: |
                python -m pip install --upgrade pip
                pip install -r DyLin/requirements.txt
                pip install -e ./DyLin
            
            - name: Checkout this repository
              uses: actions/checkout@v4
              with:
                path: 'auto_dylin'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r auto_dylin/requirements.txt
            
            - name: Modify test workflow
              run: |
                python auto_dylin/modify_test_workflow.py taget_repo/.github/workflows/${{ inputs.test_workflow }} >> $GITHUB_ENV
            
            - name: Run test workflow
              run: taget_repo/.github/workflows/${{ inputs.test_workflow }}
            
            - name: Run post-analysis
              run: |
                python auto_dylin/post_analysis.py --uid=${{ env.uid }} --test_workflow=taget_repo/.github/workflows/${{ inputs.test_workflow }} >> $GITHUB_STEP_SUMMARY
            
        
        