name: Analyze GitHub Repo

on:
    workflow_dispatch:
        inputs:
            repository:
                description: 'Repository to analyze'
                required: true
            sha:
                description: 'SHA of the commit to analyze'
                required: false
                default: ''
            test_workflow:
                description: 'Test workflow'
                required: true

jobs:
    prepare:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout target repository
              uses: actions/checkout@v4
              with:
                repository: ${{ inputs.repository }}
                ref: ${{ inputs.sha }}
                path: 'target_repo'
                sparse-checkout: '.github'
            
            - name: Checkout this repository
              uses: actions/checkout@v4
            
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                save-always: true
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ./requirements.txt
            
            - name: Install DyLin
              run: |
                python -m pip install --upgrade pip
                pip install -r ./DyLin/requirements.txt
                pip install -e ./DyLin
            
            - name: Modify test workflow
              run: |
                python ./modify_test_workflow.py --workflow_file=target_repo/.github/workflows/${{ inputs.test_workflow }}
            
            # - name: Make workflow executable
            #   run: |
            #     chmod +x target_repo/.github/workflows/${{ inputs.test_workflow }}
            
            - name: Log workflow
              run: |
                cat target_repo/.github/workflows/${{ inputs.test_workflow }}
                cp target_repo/.github/workflows/${{ inputs.test_workflow }} ./.github/workflows/test.yml
            
    run_workflow:
        uses: ./.github/workflows/test.yml
        needs: prepare
    
    post_process:
        runs-on: ubuntu-latest
        needs: run_workflow
        steps:
            - name: Run post-analysis
              run: |
                python auto_dylin/post_analysis.py --test_workflow=target_repo/.github/workflows/${{ inputs.test_workflow }} >> $GITHUB_STEP_SUMMARY
            
            - name: Save cache on failure
              if: always()
              uses: actions/cache/save@v4
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}