name: Analyze GitHub Repo

on:
    workflow_dispatch:
        inputs:
            repository:
                description: 'Repository to analyze'
                required: true
            sha:
                description: 'SHA of the commit to analyze'
                required: false
                default: ''
            test_workflow:
                description: 'Test workflow'
                required: true

jobs:
    analyze:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout target repository
              uses: actions/checkout@v4
              with:
                repository: ${{ inputs.repository }}
                ref: ${{ inputs.sha }}
                path: 'target_repo'
                sparse-checkout: '.github'
            
            - name: Checkout this repository
              uses: actions/checkout@v4
              with:
                path: 'auto_dylin'
            
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                save-always: true
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r auto_dylin/requirements.txt
            
            - name: Install DyLin
              run: |
                python -m pip install --upgrade pip
                pip install -r auto_dylin/DyLin/requirements.txt
                pip install -e auto_dylin/DyLin
            
            - name: Modify test workflow
              run: |
                ls target_repo/.github/workflows
                realpath target_repo/.github/workflows/${{ inputs.test_workflow }}
                python auto_dylin/modify_test_workflow.py --workflow_file=target_repo/.github/workflows/${{ inputs.test_workflow }}
            
            - name: Run test workflow
              run: |
                git update-index --chmod=+x ./.github/workflows/${{ inputs.test_workflow }}
                target_repo/.github/workflows/${{ inputs.test_workflow }}
            
            - name: Run post-analysis
              run: |
                python auto_dylin/post_analysis.py --test_workflow=target_repo/.github/workflows/${{ inputs.test_workflow }} >> $GITHUB_STEP_SUMMARY
            
            - name: Save cache on failure
              if: always()
              uses: actions/cache/save@v4
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}